In [1]:
import numpy as np
>>> from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
>>> from sklearn import datasets
>>> from sklearn import svm
from sklearn import cross_validation
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.cross_validation import ShuffleSplit
import matplotlib.pyplot as plt
>>> iris = datasets.load_iris()
>>> iris.data.shape, iris.target.shape
X,y = iris.data,iris.target

In [2]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)

In [3]:
from sklearn.cross_validation import ShuffleSplit
cv = ShuffleSplit(X_train.shape[0], n_iter=10, test_size=0.1275, random_state=0)

In [4]:
for train, validate in cv:
    
    clf = svm.SVC(kernel='linear', C=0.5)
    
    
    clf.fit(X_train[train],y_train[train])

In [5]:

scores = cross_val_score(clf, X_train[train],y_train[train], cv=5)

In [6]:
scores

array([ 0.95833333,  1.        ,  0.9047619 ,  1.        ,  1.        ])

In [7]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.97 (+/- 0.08)


## KNN Implementation

In [39]:
from sklearn.neighbors import KNeighborsClassifier
nbrs = KNeighborsClassifier(n_neighbors=8, algorithm='auto')  
nbrs.fit(X_train[train],y_train[train])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [40]:
knnscores = cross_val_score(nbrs, X_train[train],y_train[train], cv=5)

In [41]:
knnscores

array([ 0.95833333,  1.        ,  0.9047619 ,  1.        ,  1.        ])

In [42]:
print("Accuracy: %0.2f (+/- %0.2f)" % (knnscores.mean(), knnscores.std() * 2))

Accuracy: 0.97 (+/- 0.08)


In [47]:
testscores = cross_val_score(clf, X_test,y_test, cv=5)

In [48]:
testscores


array([ 1.  ,  1.  ,  1.  ,  1.  ,  0.75])

In [49]:
print("Accuracy: %0.2f (+/- %0.2f)" % (testscores.mean(), testscores.std() * 2))

Accuracy: 0.95 (+/- 0.20)


In [50]:
knntestscores = cross_val_score(nbrs, X_test,y_test, cv=5)

In [51]:
knntestscores

array([ 0.83333333,  0.8       ,  0.75      ,  0.75      ,  0.75      ])

In [53]:
print("Accuracy: %0.2f (+/- %0.2f)" % (knntestscores.mean(), knntestscores.std() * 2))

Accuracy: 0.78 (+/- 0.07)
